import MainHeader from "@/components/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <div>
      <MainHeader />
      {children}
    </div>
  );
}
